"""create new colum

Revision ID: 66f80c5a5bec
Revises: c45165c247c5
Create Date: 2024-10-25 00:31:51.736284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f80c5a5bec'
down_revision = 'c45165c247c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('two_factor_secret')

    # ### end Alembic commands ###
